-- Create the tasks table
-- Drop existing table and policies to avoid conflicts
DROP POLICY IF EXISTS "Allow public select" ON tasks;
DROP TABLE IF EXISTS tasks;

-- Create the new tasks table
CREATE TABLE tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name text NOT NULL,
    task_title text NOT NULL,
    task_url text NOT NULL,
    video_url text
);

-- Enable Row Level Security
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public SELECT
CREATE POLICY "Allow public select" ON tasks FOR SELECT USING (true);

-- Insert SEOFast tasks
INSERT INTO tasks (site_name, task_title, task_url, video_url) VALUES
('SEOFast', 'Task 1', 'https://seofast.ru/task1', 'https://www.youtube.com/watch?v=SB9Hyw8wQkQ'),
('SEOFast', 'Task 2', 'https://seofast.ru/task2', 'https://www.youtube.com/watch?v=ysz5S6PUM-U'),
('SEOFast', 'Task 3', 'https://seofast.ru/task3', 'https://www.youtube.com/watch?v=jNQXAC9IVRw'),
('SEOFast', 'Task 4', 'https://seofast.ru/task4', 'https://www.youtube.com/watch?v=oUFJJNQGwhk'),
('SEOFast', 'Task 5', 'https://seofast.ru/task5', 'https://www.youtube.com/watch?v=aqz-KE-bpKQ'),
('SEOFast', 'Task 6', 'https://seofast.ru/task6', 'https://www.youtube.com/watch?v=3fumBcKC6RE'),
('SEOFast', 'Task 7', 'https://seofast.ru/task7', 'https://www.youtube.com/watch?v=lTTajzrSkCw'),
('SEOFast', 'Task 8', 'https://seofast.ru/task8', 'https://www.youtube.com/watch?v=FTQbiNvZqaY'),
('SEOFast', 'Task 9', 'https://seofast.ru/task9', 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y'),
('SEOFast', 'Task 10', 'https://seofast.ru/task10', 'https://www.youtube.com/watch?v=60ItHLz5WEA');

-- Insert tasks for Aviso
INSERT INTO tasks (site_name, task_title, task_url, video_url) VALUES
('Aviso', 'Task 1', 'https://aviso.bz/task1', 'https://www.youtube.com/watch?v=ysz5S6PUM-U'),
('Aviso', 'Task 2', 'https://aviso.bz/task2', 'https://www.youtube.com/watch?v=jNQXAC9IVRw'),
('Aviso', 'Task 3', 'https://aviso.bz/task3', 'https://www.youtube.com/watch?v=oUFJJNQGwhk'),
('Aviso', 'Task 4', 'https://aviso.bz/task4', 'https://www.youtube.com/watch?v=aqz-KE-bpKQ'),
('Aviso', 'Task 5', 'https://aviso.bz/task5', 'https://www.youtube.com/watch?v=3fumBcKC6RE'),
('Aviso', 'Task 6', 'https://aviso.bz/task6', 'https://www.youtube.com/watch?v=lTTajzrSkCw'),
('Aviso', 'Task 7', 'https://aviso.bz/task7', 'https://www.youtube.com/watch?v=FTQbiNvZqaY'),
('Aviso', 'Task 8', 'https://aviso.bz/task8', 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y'),
('Aviso', 'Task 9', 'https://aviso.bz/task9', 'https://www.youtube.com/watch?v=60ItHLz5WEA'),
('Aviso', 'Task 10', 'https://aviso.bz/task10', 'https://www.youtube.com/watch?v=SB9Hyw8wQkQ');

-- Insert tasks for SocPublic
INSERT INTO tasks (site_name, task_title, task_url, video_url) VALUES
('SocPublic', 'Task 1', 'https://socpublic.com/task1', 'https://www.youtube.com/watch?v=ysz5S6PUM-U'),
('SocPublic', 'Task 2', 'https://socpublic.com/task2', 'https://www.youtube.com/watch?v=jNQXAC9IVRw'),
('SocPublic', 'Task 3', 'https://socpublic.com/task3', 'https://www.youtube.com/watch?v=oUFJJNQGwhk'),
('SocPublic', 'Task 4', 'https://socpublic.com/task4', 'https://www.youtube.com/watch?v=aqz-KE-bpKQ'),
('SocPublic', 'Task 5', 'https://socpublic.com/task5', 'https://www.youtube.com/watch?v=3fumBcKC6RE'),
('SocPublic', 'Task 6', 'https://socpublic.com/task6', 'https://www.youtube.com/watch?v=lTTajzrSkCw'),
('SocPublic', 'Task 7', 'https://socpublic.com/task7', 'https://www.youtube.com/watch?v=FTQbiNvZqaY'),
('SocPublic', 'Task 8', 'https://socpublic.com/task8', 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y'),
('SocPublic', 'Task 9', 'https://socpublic.com/task9', 'https://www.youtube.com/watch?v=60ItHLz5WEA'),
('SocPublic', 'Task 10', 'https://socpublic.com/task10', 'https://www.youtube.com/watch?v=SB9Hyw8wQkQ');